### ISSUE TITLE
Publish the project on opam-repository

### ISSUE THREAD

**Issue by kit-ty-kate** [rescript-association/reanalyze#100]
Hello, I'm one of the maintainers of https://github.com/ocaml/opam-repository and I've been using your project here and there and it looks really really good I must say.
However it is currently sadly not available through opam. Would it be possible to release it there? I can help you do that, or even do the appropriate PR for you, if needed.

**Comment by cristianoc** [comment]
Hi @kit-ty-kate thanks a lot for that!
It would be great if you could do the PR and add it to the repository.

Fwiw, this seems to work at the moment:
```
opam pin add https://github.com/reason-association/reanalyze.git
```
so the set up should not be far off.

**Comment by kit-ty-kate** [comment]
Sure, I just opened a PR here: https://github.com/ocaml/opam-repository/pull/17298

For the record, I just used opam-publish the following way:
```
$ cd reanalyze
$ git switch master && git pull origin
$ opam publish
```
This simply takes the archive from the github release and creates the PR for you.

I've made a tiny change to the opam file just to improve description and readability, I'll propose the change in a following PR here.

**Comment by kit-ty-kate** [comment]
The PR has now been merged and `reanalyze` is now available out-of-the-box on opam:
```
opam install reanalyze
```
Should I let this issue open until the next release if you want to do it yourself next time? Or should I close it?

**Comment by cristianoc** [comment]
Fantastic.
Thanks you so much @kit-ty-kate
