### ISSUE TITLE
Incorrect Division_by_zero warning in ReScript

### ISSUE THREAD

**Issue by johnridesabike** [rescript-association/reanalyze#121]
```res
let f = x => x / 2
```
```
> reanalyze -exception

  Exception Analysis
  File "test.res", line 1, characters 4-5
  f might raise Division_by_zero (test.res:1:15) and is not annotated with @raises Division_by_zero
  
  Analysis reported 1 issues (Exception Analysis:1)
```
This isn't accurate, since ReScript compiles to JS which does not raise this exception.

```js
function f(x) {
  return x / 2 | 0;
}
```

Edit: it seems to have the same problem with `mod`.

**Comment by cristianoc** [comment]
Is the comment about `2` not being zero, or JS not having a divide by zero exception?
Currently there's no special casing for specific constants and specific exceptions.
There's also no notion of exceptions only raised when compiling to native -- which could be added.

**Comment by johnridesabike** [comment]
I mean that JS doesn't have the divide by zero exception. Even if you wrote `x / 0`, the warning would still be incorrect.

**Comment by cristianoc** [comment]
Oh it throws, never mind then.

**Comment by AlexMoutonNoble** [comment]
@cristianoc is there a way to silence this error for division by e.g. literal positive ints?

**Comment by cristianoc** [comment]
You can silence it with `@doesNotRaise`.

**Comment by cristianoc** [comment]
It would be possible to specialise the analysis in the case of literal constants but seem like a not very frequent case.

**Comment by AlexMoutonNoble** [comment]
Thanks
