### ISSUE TITLE
Fatal error: exception End_of_file

### ISSUE THREAD

**Issue by zth** [rescript-association/reanalyze#128]
Hi!

```
node_modules/.bin/reanalyze -dce
Fatal error: exception End_of_file
```

This is running Reanalyze in a mid-sized project. Since the error is quite sparse, what can I do to help debug it? What type of information can I supply?

**Comment by cristianoc** [comment]
Try to deep clean and rebuild the project.
Other than that, use `-debug`.

**Comment by cristianoc** [comment]
Also: is this ReScript or a native project? (In the latter case you need reanalyze built against the same ocaml compiler version).

**Comment by zth** [comment]
It's ReScript. Let me try that and get back with the results.

**Comment by zth** [comment]
I cleaned and wiped node_modules etc, and it seems to work now! Thanks!

**Comment by AlexMoutonNoble** [comment]
Just another note here for history:  It seems to be the clean for me, not the node_modules.
