### ISSUE TITLE
@dead annotation breaks rescript compiler on a destructured value

### ISSUE THREAD

**Issue by JonoPrest** [rescript-association/reanalyze#162]
Sometimes there is an unused value in our project that is being destructured from a module. The @dead annotation from reanalyze -dce -write will be placed next to the destructured value and then the rescript file is unable to compile.

```res
let {@dead("+toNumber") toNumber} = module(Ethers.BigNumber)
```

I'm not sure what can be done about this but it seems to work fine if the destructured value is named like this:

```res
let {toNumber: @dead("+toNumber") toNumber} = module(Ethers.BigNumber)
```

**Comment by cristianoc** [comment]
1 don't destroy the annotation on formatting
2 allow parsing punned fields with annotations

**Comment by JonoPrest** [comment]
Ah I see, thanks for your quick response @cristianoc 🙏
