### ISSUE TITLE
Interface of sub module are not seen used

### ISSUE THREAD

**Issue by florentbarriol** [rescript-association/reanalyze#186]
Hello :wave: ,
We use `renalyze` in our CI at [Arte TV](https://www.arte.tv).
And we face an issue with interface (.resi) of submodule.
They do not seem to be seen by the analyze even if they are well used.

I create an example repository to illustrate the issue : https://github.com/florentbarriol/issue-interface-submodule

We find a workaround for now. We use inline interface and  not .resi files.
You will find an example in the repository.

Hope, you will find a solution because we love the projet.
It's very helpful :heart:

**Comment by cristianoc** [comment]
@florentbarriol the analysis has moved inside the editor extension. The fix is here: https://github.com/rescript-lang/rescript-vscode/pull/650

**Comment by cristianoc** [comment]
The executable used by the editor extension has an option `reanalyze`. This is only used to test the extension at the moment, but could be used in CI as well as long as you get the extension's executable there.
E.g. on my machine:
```
~/.vscode/extensions/chenglou92.rescript-vscode-1.9.35/server/analysis_binaries/darwinarm64/rescript-editor-analysis.exe reanalyze -help
```

**Comment by florentbarriol** [comment]
Thanks for your work !
