### ISSUE TITLE
Catching on exception from other module leads to incorrect warning

### ISSUE THREAD

**Issue by fhammerschmidt** [rescript-association/reanalyze#188]
Consider the following example:

```res
module Test = {
  exception Nested

  @raises(Nested)
  let raises = async () => raise(Nested)
}

let raises = async () =>
  try await Test.raises() catch {
  | Test.Nested => Js.log("Not found")
  }
```

it gives me: 
`raises might raise Nested (test.res:9:12) and is not annotated with @raises(Nested)`

However, if I `open Test` instead:

```res
module Test = {
  exception Nested

  @raises(Nested)
  let raises = async () => raise(Nested)
}

open Test

let raises = async () =>
  try await Test.raises() catch {
  | Nested => Js.log("Not found")
  }
```

Everything works fine

**Comment by cristianoc** [comment]
The exception analysis has a simple model for exception paths, which are taken literally.
It does not try to resolve scope or aliasing.

**Comment by cristianoc** [comment]
Btw the analysis is now integrated in the editor extension, so this could be moved there.

**Comment by fhammerschmidt** [comment]
Ok, closing this in favor of https://github.com/rescript-lang/rescript-vscode/issues/716
